# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.6

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.cache/pip/
  - node_modules/
  - elm-stuff/

stages:
  - build
  - test
  - deploy

python:
  stage: build
  image: python:3.6
  cache:
    untracked: true
  script:
    - python -V # Print out python version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv/lib/python3.6/site-packages
      - venv/bin

elm:
  stage: build
  image: node:9.4
  cache:
    untracked: true
  script:
    - npm install elm
    - node_modules/elm/binwrappers/elm-package install -y
    - node_modules/elm/binwrappers/elm-make frontend/src/Main.elm --output testr/core/static/js/main.js
  artifacts:
    paths:
      - testr/core/static/js/main.js

unit:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: nice_marmot
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST: postgres
    DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB
  script:
    - source venv/bin/activate
    - sleep 1
    - venv/bin/coverage run --source='./testr' manage.py test
    - venv/bin/coverage report

ui:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: nice_marmot
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST: postgres
    DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB
  script:
    - source venv/bin/activate
    - pip -V # check to see if we're in a virtualenv
    - sleep 1
    - python manage.py behave

staging:
  stage: deploy
  type: deploy
  only:
    - master
  dependencies:
    - elm
  script:
    - apt-get update -qy
    - apt-get install -y ruby ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_STAGING_APP --api-key=$HEROKU_STAGING_API_KEY

production:
  stage: deploy
  type: deploy
  only:
    - tags
  dependencies:
    - elm
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_PRODUCTION_APP --api-key=$HEROKU_PRODUCTION_API_KEY
